// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utidymwvrwcpoibyzxsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aWR5bXd2cndjcG9pYnl6eHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTQyMjAsImV4cCI6MjA1OTY5MDIyMH0.AtP8FZfDWo9osFEhrJJiKaUWz0utGCgj0rdvYBQnfzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);